app/models.py
from . import db
from datetime import datetime

class Student(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    rollno = db.Column(db.String(20),unique=True,nullable=False)
    name = db.Column(db.String(100),nullable=False)
    feesamount=db.Column(db.Float,nullable=False)
    dated = db.Column(db.DateTime, default=datetime.utcnow)
    paymentmode = db.Column(db.String(50), nullable=False)
    def __repr__(self):
        return f'<Student{self.name}>'

app/forms.py
from flask_wtf import  FlaskForm
from wtforms import StringField, FloatField, SelectField, SubmitField
from wtforms.validators import DataRequired
#Class 1
class StudentForm(FlaskForm):
    rollno = StringField('Rollno', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    feesamount = FloatField('Fees Amount', validators=[DataRequired()])
    paymentmode = SelectField('Payment Mode', choices=[('Cash','Cash'),('Card','Card')], validators=[DataRequired()])
    submit=SubmitField('Submit')
#Class 2
class SearchForm(FlaskForm):
    search = StringField('Search By Roll No Or Name',validators=[DataRequired()])
    submit=SubmitField('Search')

#Class N
        



app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
db=SQLAlchemy()
def create_app():
    app=Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///student1.db'
    app.config['SECRET_KEY']='bhumi_ankita'
    db.init_app(app)
    Bootstrap(app)
    from .routes import main
    app.register_blueprint(main)
    return app

app/routes.py
from flask import Blueprint,render_template,redirect,url_for,request,flash
from .models import Student
from .forms import StudentForm,SearchForm
from .import db 
from fpdf import FPDF
main =Blueprint('main',__name__)
@main.route('/')
def index():
    form= SearchForm()
    students = Student.query.all()
    return render_template('index.html',students=students,form=form)
@main.route('/add', methods=['GET','POST'])
def add_students():
    form = StudentForm()
    if form.validate_on_submit():
        new_student = Student(rollno=form.rollno.data,name=form.name.data,feesamount=form.feesamount.data,paymentmode=form.paymentmode.data)
        db.session.add(new_student)
        db.session.commit()
        flash("student successfully added!","success")
        return redirect(url_for('main.index'))
    return render_template('add_update.html',form=form,title="Add Student")
@main.route('/update/<int:id>',methods=['GET','POST'])
def update_student(id):
    student = Student.query.get_or_404(id)
    form  = StudentForm(obj=student)
    if form.validate_on_submit():
        student.rollno = form.rollno.data
        student.name = form.name.data
        student.feesamount = form.feesamount.data
        student.paymentmode = form.paymentmode.data
        db.session.commit()
        flash("student updated successfully!", "success")
        return redirect(url_for('main.index'))
    return render_template('add_update.html',form=form,title="Update Student")
@main.route('/delete/<int:id>')
def delete_student(id):
    student = Student.query.get_or_404(id)
    db.session.delete(student)
    db.session.commit()
    flash("student deleted successfully!", "danger")
    return redirect(url_for('main.index'))
@main.route('/search',methods=['POST'])
def search_student():
    form = SearchForm()
    search_term = form.search.data
    students = Student.query.filter((Student.rollno.contains(search_term)))| ((Student.name.contains(search_term))).all()
    return render_template('index.html',students=students,form=form)

@main.route('/export')
def export_to_pdf():
    students=Student.query.all()
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size = 12)
    pdf.cell(200, 10, txt = "Student Records", ln = True, align="C")
    for student in students:
        pdf.cell(200,10,text=f"{student.rollno} - {student.name} - {student.feesamount} - {student.paymentmode}", ln=True)
        pdf_file = "students_report.pdf"
        pdf.output(pdf_file)
        return redirect(url_for('main.index'))





app/templates/add_update.html
{% extends 'base.html'%} {% block title %}{{title}}{% endblock %}
{% block content %}
<form action="" method="POST">
  {{form.hidden_tag()}}
  <div class="mb-3">
    {{form.rollno.label(class="form-label")}}
    {{form.rollno(class="form-control")}}
  </div>
  <div class="mb-3">
    {{form.name.label(class="form-label")}} 
    {{form.name(class="form-control")}}
  </div>
  <div class="mb-3">
    {{form.feesamount.label(class="form-label")}}
    {{form.feesamount(class="form-control")}}
  </div>
  <div class="mb-3">
    {{form.paymentmode.label(class="form-label")}}
    {{form.paymentmode(class="form-select")}}
  </div>

  <div>{{ form.submit(class="btn btn-primary")}}</div>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Student Management{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Student Management</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li  class="navbar-item">
                        <a class="nav-link" href="/add">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/add">Add Student</a>
                            </li></ul></div></div></nav>
                            <div class="container mt-4">
                                {% with messages = get_flashed_messages(with_categories=true) %}
                                {% if messages %}
                                {% for category, message in messages %}
                                <div class="alert alert-{{category}}">{{message}}</div>
                                {%endfor%}
                                {%endif%}
                                {%endwith%}
                                {%block content%}
                                {%endblock%} </div> 
                                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
                                                          
</body>
</html>     

app/templates/index.html
{%extends 'base.html'%} {%block title%}Home{%endblock%} {%block content%}
<form action="{{url_for('main.search_student')}}" methods="POST">
  {{form.hidden_tag()}}
  <div calss="mb-3">
    {{form.search(class="form-control",placeholder="Search By Roll Number Or
    Name")}}
    </div>
    <div>
        {{form.submit(class="btn btn-primary")}}

    </div>
    </form>
    <table class="table table-striped mt-4">
        <thead> <tr>
            <th>Roll Number</th>
            <th>Name</th>
            <th>Fess Amount</th>
            <th>Payment Mode</th>
            <th>Actions</th> </tr>
        </thead><tbody>
            {%for student in students%}
            <tr><td>{{student.rollno}}</td><td>{{student.name}}</td>
            <td>{{student.feesamount}}</td><td>{{student.paymentmode}}</td>
            <td>
                <a href="{{url_for('main.update_student',id=student.id)}}" class="btn btn-warning">Edit</a>
                <a href="{{url_for('main.delete_student',id=student.id)}}" class="btn btn-danger">Delete</a>

            </td>    
            </tr>
            {%endfor%}
            </tbody>
    </table>
    <a href="{{url_for('main.export_to_pdf')}}" class="btn btn-secondary">Export to PDF</a>
{%endblock%}
